Repository wazo-platform/wazo-test-helpers, pull requests merged in 2021-04, with the labels that each got.

#50 wazo-auth: update deprecated acls to acl
  contribs/docker/wazo-auth-mock/wazo-auth-mock.py
  xivo_test_helpers/auth.py
Labels: auto-merge, mergeit

#51 auth mock: allow setting session uuid
  xivo_test_helpers/asset_launching_test_case.py
  xivo_test_helpers/auth.py
Labels: auto-merge

#52 Pull request for add-note-about-service-port
  README.md
  xivo_test_helpers/asset_launching_test_case.py
Labels: mergeit
